# Generated by Django 6.0.7 on 2026-08-01 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text="Nombre de jours d'accès offerts par ce plan.")),
                ('is_active', models.BooleanField(default=True, help_text="Permet de retirer un plan de la vente sans le supprimer (garde l'historique intact).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text="Vide pour l'essai gratuit initial (pas de plan payant associé).", null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
