# Generated by Django 6.0.7 on 2026-07-23 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalOperation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_type', models.CharField(choices=[('UPDATE_STORE', 'Modifier une boutique')], max_length=30)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('applied', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('client_created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_operations', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client_created_at'],
            },
        ),
    ]
