# Generated by Django 6.0.7 on 2026-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaloperation',
            name='operation_type',
            field=models.CharField(choices=[('UPDATE_STORE', 'Modifier une boutique'), ('CREATE_CATEGORY', 'Créer une catégorie'), ('UPDATE_CATEGORY', 'Modifier une catégorie')], max_length=30),
        ),
    ]
