# Generated by Django 6.0.7 on 2026-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_journaloperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaloperation',
            name='operation_type',
            field=models.CharField(choices=[('UPDATE_STORE', 'Modifier une boutique'), ('CREATE_CATEGORY', 'Créer une catégorie'), ('UPDATE_CATEGORY', 'Modifier une catégorie'), ('CREATE_PRODUCT', 'Créer un produit'), ('UPDATE_PRODUCT', 'Modifier un produit')], max_length=30),
        ),
    ]
