# Generated by Django 6.0.7 on 2026-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_alter_journaloperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaloperation',
            name='operation_type',
            field=models.CharField(choices=[('UPDATE_STORE', 'Modifier une boutique'), ('CREATE_CATEGORY', 'Créer une catégorie'), ('UPDATE_CATEGORY', 'Modifier une catégorie'), ('CREATE_PRODUCT', 'Créer un produit'), ('UPDATE_PRODUCT', 'Modifier un produit'), ('CREATE_SUPPLIER', 'Créer un fournisseur'), ('UPDATE_SUPPLIER', 'Modifier un fournisseur'), ('CREATE_CUSTOMER', 'Créer un client'), ('UPDATE_CUSTOMER', 'Modifier un client'), ('CREATE_SALE', 'Créer une vente'), ('CREATE_RESTOCK', 'Réapprovisionner'), ('CREATE_ADJUSTMENT', 'Ajuster le stock'), ('CREATE_INVENTORY_COUNT', "Comptage d'inventaire")], max_length=30),
        ),
    ]
