# Generated by Django 6.0.7 on 2026-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_alter_journaloperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaloperation',
            name='operation_type',
            field=models.CharField(choices=[('UPDATE_STORE', 'Modifier une boutique'), ('CREATE_CATEGORY', 'Créer une catégorie'), ('UPDATE_CATEGORY', 'Modifier une catégorie'), ('CREATE_PRODUCT', 'Créer un produit'), ('UPDATE_PRODUCT', 'Modifier un produit'), ('CREATE_SUPPLIER', 'Créer un fournisseur'), ('UPDATE_SUPPLIER', 'Modifier un fournisseur'), ('CREATE_CUSTOMER', 'Créer un client'), ('UPDATE_CUSTOMER', 'Modifier un client'), ('CREATE_SALE', 'Créer une vente'), ('CREATE_RESTOCK', 'Réapprovisionner'), ('CREATE_ADJUSTMENT', 'Ajuster le stock'), ('CREATE_INVENTORY_COUNT', "Comptage d'inventaire"), ('CREATE_EXPENSE', 'Créer une dépense'), ('UPDATE_EXPENSE', 'Modifier une dépense'), ('DELETE_EXPENSE', 'Supprimer une dépense'), ('CREATE_CASH_SESSION', 'Ouvrir une session de caisse'), ('CLOSE_CASH_SESSION', 'Fermer une session de caisse'), ('CREATE_PURCHASE', 'Créer un achat'), ('CREATE_EMPLOYEE', 'Créer un employé'), ('UPDATE_EMPLOYEE', 'Modifier un employé'), ('DELETE_EMPLOYEE', 'Supprimer un employé'), ('CREATE_PAYMENT', 'Enregistrer un paiement')], max_length=30),
        ),
    ]
