# Generated by Django 6.0.7 on 2026-08-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('revoked', 'Révoquée'), ('rejected', 'Rejetée')], default='pending', max_length=10),
        ),
    ]
