# Generated by Django 6.0.7 on 2026-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_stockmovement_note_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date de péremption (facultative — secteurs concernés uniquement)', null=True),
        ),
    ]
