# Generated by Django 6.0.7 on 2026-08-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_purchase_purchaseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.purchase'),
        ),
    ]
