# Generated by Django 6.0.7 on 2026-08-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_stockmovement_new_purchase_price_and_more'),
        ('stores', '0002_storeinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dette envers ce fournisseur (achats à crédit non réglés)', max_digits=12),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('CUSTOMER_PAYMENT', 'Encaissement client'), ('SUPPLIER_PAYMENT', 'Règlement fournisseur')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('OTHER', 'Autre')], default='CASH', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='catalog.customer')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='catalog.purchase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='catalog.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stores.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='catalog.supplier')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
