# Generated by Django 6.0.7 on 2026-08-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_storeinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_member', models.ForeignKey(blank=True, help_text="Compte gérant lié (optionnel) — si cette personne a aussi accès à l'app.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='stores.userstore')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='stores.store')),
            ],
        ),
    ]
